
export const siteConfig = {
	name: "Jeremy Traini",
	title: "Jeremy Traini | Software Engineer in Sydney",
	description: "Jeremy Traini is a Sydney-based software engineer and UNSW student building full-stack products across analytics, fintech, education and developer tooling.",
	url: "https://jeremytraini.com",
	ogImage: "/images/thumbnails/jeremytraini.png",
	email: "hi@jeremytraini.com",
	applicationName: "Jeremy Traini",
	keywords: [
		"Jeremy Traini",
		"Jeremy Traini software engineer",
		"Jeremy Traini portfolio",
		"Sydney software engineer",
		"software engineer Sydney",
		"software developer Sydney",
		"full stack developer Sydney",
		"full-stack software engineer",
		"UNSW software engineering",
		"software engineer portfolio",
		"software developer portfolio",
		"web developer Sydney",
		"frontend developer Sydney",
		"backend developer Sydney",
		"full-stack developer Australia",
		"fintech software engineer",
		"product engineer portfolio",
		"UNSW student developer",
	],
	authors: [{ name: 'Jeremy Traini' }],
	creator: 'Jeremy Traini',
	links: {
		github: "https://github.com/jeremytraini",
		linkedin: "https://www.linkedin.com/in/jeremytraini",
		dribbble: "https://dribbble.com/jeremytraini",
	},
	navItems: [
		{
			label: "Me",
			href: "#",
		},
		{
			label: "Timeline",
			href: "#timeline",
		},
		{
			label: "Work",
			href: "#work",
		},
		{
			label: "Contact",
			href: "#contact",
		},
	],
	timelineLineColour: "border-blue-900",
};
