
export const siteConfig = {
	name: "Jeremy Traini",
	title: "Jeremy Traini | Software Engineer in Sydney",
	description: "Jeremy Traini is a Sydney-based software engineer and UNSW student building full-stack products across analytics, fintech, education and developer tooling.",
	url: "https://jeremytraini.com",
	ogImage: "/images/thumbnails/jeremytraini.png",
	email: "hi@jeremytraini.com",
	jobTitle: "Software Engineer",
	location: {
		city: "Sydney",
		region: "NSW",
		country: "AU",
	},
	applicationName: "Jeremy Traini",
	keywords: [
		"Jeremy Traini",
		"Jeremy Traini software engineer",
		"Jeremy Traini portfolio",
		"Sydney software engineer",
		"software engineer Sydney",
		"software developer Sydney",
		"full stack developer Sydney",
		"full-stack software engineer",
		"UNSW software engineering",
		"software engineer portfolio",
		"software developer portfolio",
		"web developer Sydney",
		"frontend developer Sydney",
		"backend developer Sydney",
		"full-stack developer Australia",
		"fintech software engineer",
		"product engineer portfolio",
		"UNSW student developer",
	],
	authors: [{ name: 'Jeremy Traini' }],
	creator: 'Jeremy Traini',
	knowsAbout: [
		"Full-stack software engineering",
		"Product engineering",
		"Mobile app development",
		"Analytics platforms",
		"Fintech products",
		"Developer tooling",
		"React Native",
		"React",
		"TypeScript",
		"JavaScript",
		"C#",
		"Python",
		"Firebase",
		"AWS",
		"Terraform",
		"Machine learning pipelines",
	],
	awards: [
		"UNSW Business School Dean's Award for Academic Excellence (2025)",
		"Third Year Software Engineering Optiver Prize Finalist (2024)",
		"Faculty of Engineering Dean's Honours List, Highly Commended (2025, 2023, 2021)",
		"Macquarie Bank Second Year Software Engineering Prize (2023)",
		"UNSW New College Academic Prize in Engineering (2022)",
	],
	links: {
		github: "https://github.com/jeremytraini",
		linkedin: "https://www.linkedin.com/in/jeremytraini",
	},
	navItems: [
		{
			label: "Me",
			href: "#",
		},
		{
			label: "Timeline",
			href: "#timeline",
		},
		{
			label: "Work",
			href: "#work",
		},
		{
			label: "Contact",
			href: "#contact",
		},
	],
	timelineLineColour: "border-blue-900",
};
